[variables]
NIXPACKS_PYTHON_VERSION = "3.10"

[phases.setup]
nixPkgs = ["python310", "tesseract", "poppler_utils"]

[phases.install]
cmds = [
    "pip install -r backend/requirements.txt"
]

[phases.build]
cmds = [
    "mkdir -p backend/data backend/uploads backend/logs"
]

[start]
cmd = "cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT"